// File generated by hand from the Firebase console's per-platform app
// configs (Project settings → Your apps), following the same shape the
// `flutterfire configure` CLI would normally generate. iOS isn't
// registered in Firebase yet — that needs a Mac (Xcode) to build at all,
// so it's deferred until this app is actually built for iOS.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS isn\'t registered in Firebase yet — add an iOS app (bundle ID) '
          'in the Firebase console under Project settings, then fill in '
          'FirebaseOptions.ios below with the values it gives you.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyCFTrse62kuL22PUsWDbuRfxPMKtoKOPF4',
    appId: '1:920109932625:web:a7b30ef10c24f26d5f5870',
    messagingSenderId: '920109932625',
    projectId: 'al-sharqawi-tech',
    authDomain: 'al-sharqawi-tech.firebaseapp.com',
    storageBucket: 'al-sharqawi-tech.firebasestorage.app',
    measurementId: 'G-RKJ0WGNKB6',
  );

  // Mirrors android/app/google-services.json — that file is what the
  // native Android build actually reads; this is what the Flutter-side
  // firebase_core plugin needs when initializeApp() is called with
  // explicit options (kept identical across platforms, same as web/ios).
  static const android = FirebaseOptions(
    apiKey: 'AIzaSyBJM43M7tuwUhdfg4c_M4dc4CuDpR74g2k',
    appId: '1:920109932625:android:d3e5f9e809e880e05f5870',
    messagingSenderId: '920109932625',
    projectId: 'al-sharqawi-tech',
    storageBucket: 'al-sharqawi-tech.firebasestorage.app',
  );
}
